### PR TITLE
Improved performance in album load

### PR DESCRIPTION
**Pull request by kfriedenberger**
Removed nested loop for thumbnail retrieval

### CODE REVIEW

**Comment by electerious** [comment]
Maybe I'm missing something, but it looks like the implementation is missing the sorting of the thumbs (`$this->settings['sortingPhotos']`). The first 3 thumbs are always the first 3 photos of the album, based on the photo-sorting. https://github.com/electerious/Lychee/pull/372/files#diff-c2d1bf354e4b5d583df1a7213adec491L213

**Comment by kfriedenberger** [comment]
Will add that in; I had accounted only for the album sort.

Kirk

----------------------
Kirk Friedenberger
312.925.2661

**Comment by electerious** [comment]
This was the part I couldn't get working. Maybe you have more luck.

**Comment by kfriedenberger** [comment]
Yes I have it working -- question though, should the thumbs sort by star
DESC, then the photo sorting order setting? Or just the photo order
setting. Meaning if there are favorites in the album, should they appear as
the preferred thumbnails?

On Wed, Jul 1, 2015 at 2:26 PM, Tobias Reich <notifications@github.com>
wrote:

> This was the part I couldn't get working. Maybe you have more luck.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/electerious/Lychee/pull/372#issuecomment-117800688>.
>



-- 
Kirk Friedenberger

**Comment by electerious** [comment]
Favorites should have a higher priority, no matter what the sorting says.

**Comment by electerious** [comment]
@kfriedenberger Can you add your updated version to the PR?

**Comment by electerious** [comment]
@kfriedenberger Any news?

**Comment by kfriedenberger** [comment]
I've moved to another platform but will dig up the code and send across.

Thanks.
Kirk

----------------------
Kirk Friedenberger
312.925.2661

**Pull request closed without merging**
