### PR TITLE
Prefetch the medium photo instead of the big one

### PR DESCRIPTION
**Pull request by Bramas**
This PR is related to the issue #185 
I added the medium photo url in each photo of the album,
Then this url is used instead of the big photo url when prefetching the next photo.

The problem is that we don't know which photo is loaded by the browser because some browsers don't understand srcset with 'w' parameter.
But I think it's better to preload the medium and hope for the browser to use it (possible 1~2 Mo lost on old browser or on 4K screen if not), instead of preloading the big one and lose 10 Mo every photo on a recent browser.

### CODE REVIEW

**Comment by Bramas** [comment]
Also, In the case the screen of the user is bigger that 1920px then the prefetched medium photo is lost.
What we can do is add a media query in the link: `<link rep='prefetch' media='(max-width: 1920px)' MEDIUM_URL>`
and we can even add another link  `<link rep='prefetch' media='(min-width: 1920px)' BIG_URL>`

**Comment by electerious** [comment]
Do you know if `rel="prefetch"` and `media='(min-width: 1920px)'` works together? I never heard about this combination. Would be great, thought.

**Comment by Bramas** [comment]
I just checked it out and unfortunately `rel="prefetch"` and `media='(min-width: 1920px)'` do not work together. It is even worse, because even when using `rel="stylesheet"` with the media attribute, even if the condition of the media query is not satisfied, the stylesheet **is downloaded**. So it cannot prevent the prefetch of a photo.
If we want to prefetch the right picture depending on the viewport, we will have to wait for a way to detect which picture has been loaded by the browser with the srcset attribute, and then use this to prefetch the other photos (found nothing on stackoverflow about that). Maybe the html5 element `picture` can help detecting which image has been loaded.

Without more information, I think the medium photo is the right one to prefetch.

**Comment by electerious** [comment]
Implemented. Can you take a look at it?

**Pull request closed without merging**
