### PR TITLE
Allow browser to save passwords

### PR DESCRIPTION
**Pull request by Klikini**
This has been tested in Chrome and it will trigger the "save password" window:

image

Fixes https://github.com/electerious/Lychee/issues/456

### CODE REVIEW

**Comment by electerious** [comment]
You need to [rebuild Lychee](https://github.com/electerious/Lychee/blob/develop/docs/Build.md) to see your changes. Tested it in Safari and Firefox. Issue still exists :-/

**Comment by Hund** [comment]
How's it going with this? :)

**Comment by Klikini** [comment]
@Hund I don't have access to Safari, and Firefox detects passwords differently (I'm not sure how), sorry.

**Comment by Hund** [comment]
Oh. I have this issue with the  Firefox based browser Pale Moon.

**Pull request merged**
