### PR TITLE
Added support for selecting photos/albums individually

### PR DESCRIPTION
**Pull request by hrniels**
Note that the commit is on top of the "Better highlighting of selected items", because it uses two functions that were introduced there. Apart from that, they are independent.

### CODE REVIEW

**Comment by electerious** [comment]
How do I select photos individually?

**Comment by electerious** [comment]
Not a fan of the 2px border. Title and date jumps around when selecting a photo. Maybe a different color for the selection instead? Blue for the border and white for the selection "overlay"?

**Comment by electerious** [comment]
`outline: 1px solid #2293EC;` could be a solution. Adds another "border" without changing the position of the inner content.

**Comment by hrniels** [comment]
> How do I select photos individually?

Use ctrl+click.

> `outline: 1px solid #2293EC;` could be a solution. Adds another "border" without changing the position of the inner content.

Yes, that looks better :)

**Comment by electerious** [comment]
> Use ctrl+click.

The context menu opens directly when ctrl-clicking an photo/album and the others aren't clickable when the menu is open.

**Comment by hrniels** [comment]
Are you using the left mouse button?

**Comment by electerious** [comment]
Yes. Tried it in Safari and Chrome. Both are opening the menu directly.

**Comment by hrniels** [comment]
I'm using Chromium, so that shouldn't be the problem. Are you sure you use the correct branch and have rebuild the js files in dist? ;)

**Comment by electerious** [comment]
ctrl + left mouse click triggers a right-click on OS X. Could this be the problem?

**Comment by hrniels** [comment]
Ah, might be. I have no chance to test that here. But IMO ctrl+click should be used on Linux and Windows, because it's the usual way to select multiple things. What to do for OS X? Is there already an API that does the expected thing depending on the OS or do we have to do that ourself?

**Comment by electerious** [comment]
I'm not aware of an API. On OS X you can select multiple items using cmd + left-click. I remember seeing other web apps using shift + left-click to work around the problem.

**Comment by hrniels** [comment]
Do you want to add the code for OS X? Unfortunately, I wouldn't be able to test it...

**Comment by electerious** [comment]
Merged it into subalbums and made a few adjustments:

- We now use the shift-key to select photos/albums individually. It's the only one that works on every  OS. Adding a OS detection isn't a good idea.
- Removed select all. Makes no sense anymore as albums can contain albums and photos and you can only select one type.
- Branch now up-to-date with develop.
- Version pushed to v3.2.0

**Comment by electerious** [comment]
Big thanks for implementing this feature. It works really really good. Such a big improvement :)

One change I would like to propose (maybe you can take care of it): Selecting by dragging shows the context-menu directly. It would be better to just select the photos/albums, like we do when shift-clicking them. This would allow the user to select additional ones with another selection.

**Comment by hrniels** [comment]
> We now use the shift-key to select photos/albums individually. It's the only one that works on every OS. Adding a OS detection isn't a good idea.

hm. Why not register all three keys (ctrl, shift, command) for that? That should make everybody happy. Because shift+click for selecting items individually is strange IMO.

> Big thanks for implementing this feature. It works really really good. Such a big improvement :)

You're welcome :)

> One change I would like to propose (maybe you can take care of it): Selecting by dragging shows the context-menu directly. It would be better to just select the photos/albums, like we do when shift-clicking them. This would allow the user to select additional ones with another selection.

Yes, that's a good idea. I can do that. Should be simple.

**Comment by electerious** [comment]
> hm. Why not register all three keys (ctrl, shift, command) for that? That should make everybody happy. Because shift+click for selecting items individually is strange IMO.

Found the perfect solution: https://api.jquery.com/event.metakey/ :)) Going to implement it.

**Comment by electerious** [comment]
https://github.com/electerious/Lychee/commit/ff5637a7daf0ab45d6feb36771cbdbf3d7b932a6

**Comment by electerious** [comment]
✅ This PR is complete. More in https://github.com/electerious/Lychee/pull/603

**Pull request merged**
