### PR TITLE
Various fixes for php 32bits and long albums/photos ids

### PR DESCRIPTION
**Pull request by karlak**
(love your project btw)
The ids have to be integers as this is what the javascript part expect. (When creating an album for instance.)

edit:
Just realized it breaks staring photos. "0"s & "1"s are passed through json to javascript.
I'll look into it soon.

edit2:
On an other topic, using "prerender" instead of "prefetch" decrease considerably the time needed to show the next/previous photo.

### CODE REVIEW

**Comment by electerious** [comment]
Are there any problems with the current implementation? Adding a new album seems to work fine.

**Comment by electerious** [comment]
[prefetch](http://caniuse.com/#feat=link-rel-prefetch) is also supported by Firefox, which is not the case for `prerender`. Is there a way to support both?

**Comment by karlak** [comment]
Php 32 bits can't handle large numbers as the ids. 14 digits si too much. 
I heard Php 6 will manage long type, but for now large numbers are often represented as strings.
When tested Lychee for the first time, I could'nt do much. The function generateId always returned the max (32bits) integer value (2,147,483,647) which broke everything. (aaand I just realized I didn't commit'd that fix, sry -_-").
To fix this, I think you can only change the function generateId to return a string. Then two possibilities:
- change it back to a large integer in json with the right flag
- change the javascript part which verify the type of this value (returned by (at least) Albums::add)


For the prerender part, I don't know much. I tested it quickly on chrome and after further investigations it is indeed not supported by all browsers. I've seen people use both.

**Comment by qligier** [comment]
Using both _prefetch_ and _prerender_ seems indeed the best solution, as they don't have the same browser support nor the same behavior (as one of my teachers likes to say, _he who can do more can do less_).

Also, it's useless to [left-padd the generated ID with zeros](/electerious/Lychee/blob/develop/php/helpers/generateID.php#L9) if you convert it to int.

**Comment by electerious** [comment]
@karlak This problem isn't new in 3.1, right? We are using large numbers for the photo IDs since the beginning of the project. I wonder why no one reported this problem before.

@qligier The function adds zeros to the end of the ID. The ID stays the same when converting to a int.

**Comment by karlak** [comment]
@qligier The microtime(true) function returns a float, which when casted to a string can have various size. Getting them all to the same size allow for comparison and sorting of the ids by creation date. At least I think that's the reason this is done that way.
```php
$t = $microtime(true); // ex:  1458125612.4 or 1458125612.4005 (slightly different)
$id = str_replace('.', '', $t); // gives 14581256124 or 14581256124005 (not comparable anymore)
// Ensure that the id has a length of 14 chars
while(strlen($id)<14) $id .= 0; // 145812561240000 or 14581256124005 (again slightly different)

return intval($id); // always return 2147483647 (PHP_INT_MAX) in 32 bits
```

@electerious This problem only occurs in the develop branch.
In the master branch the id is handled as a string all the way and echoed to the client.
Whereas in the develop branch the id is immediately casted to an int in order to be sent correctly by the function json_encode of the Response class. (without quotes)

**Comment by qligier** [comment]
Yep, I don't know why, I thought the ID was being left-padded with zeros, that would have made no sense. I wasn't fully awake, sorry for that :/

**Comment by electerious** [comment]
@karlak Thanks for the explanation. Got it! `JSON_NUMERIC_CHECK` sounds like a valid solution. I just need to ensure that this won't cause any other problems. Give me some time so I can take a deeper look at it.

You mentioned that you don't committed a fix "aaand I just realized I didn't commit'd that fix, sry -_-).". Is there anything missing or is the PR complete?

**Comment by karlak** [comment]
I'll post an other pull request with a working solution today or tomorrow. Putting `JSON_NUMERIC_CHECK ` every time causes problems to other json exchanges.

**Comment by electerious** [comment]
Please take a look at the newest develop-branch commit (https://github.com/electerious/Lychee/commit/c6d8b5f3122614222f9f79ad6651cc2780d4debd). Does it work now? Is there another place where we need to fix it?

**Comment by electerious** [comment]
We're now also returning the id for successful photo uploads (like we do for successful new album creation). Should work too with the newly added fix: https://github.com/electerious/Lychee/commit/d212363ebf50b531d144d1429340ba1f19eb6071

**Comment by karlak** [comment]
Perfect ! Works like a charm.
Thank you for your work.

**Comment by electerious** [comment]
🎉 Guess v3.1 is more or less ready. Going to release it next week. Let me know if you find any other bug and thanks for the report!

**Pull request closed without merging**
