### PR TITLE
Better EXIF extraction

### PR DESCRIPTION
**Pull request by qligier**
Small rewrite of EXIF extraction and a few improvements.
- No need to create temp variable to check if array element exists
- No error suppression #515
- Import photo tags (works with Lightroom, maybe also with others softwares) #514 
- Converting GPS coordinates to float number of degrees #494 

Tested with a few photos, without bugs.

### CODE REVIEW

**Comment by electerious** [comment]
Looks great, but I'm getting a few errors when trying to upload photos:

```
[18-Apr-2016 07:39:05 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:16 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:16 UTC] PHP Warning:  exif_read_data(578c31ef8360e74356ff0d7a3cb0753f.jpg): Incorrect APP1 Exif Identifier Code in /Users/tobiasreich/Sites/lychee/php/Modules/Photo.php on line 786
[18-Apr-2016 07:39:16 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:17 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:18 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:20 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:20 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:22 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:24 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
[18-Apr-2016 07:39:26 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /Users/tobiasreich/Sites/lychee/php/Modules/Database.php on line 336
```

**Comment by qligier** [comment]
It seems to be caused by the photo, can I get it? I'll do some adjustment on the code.

**Comment by electerious** [comment]
Seems to happen with several test-images. Here're two of them (The second one is transparent):
iptc
transparent

**Comment by qligier** [comment]
exif_read_data throws uncatchable warnings when EXIF data don't exists or are malformed, so we have to suppress the errors for this.
I also have errors shown when I add a photo. The photo is correctly added and the AJAX returns the new ID but it shows "Server returned an unknown response. Please take a look at the console of your browser for further details."
Not sure if caused by my PR.

**Comment by electerious** [comment]
Any way to reproduce it? My test-photos are uploading without errors.

**Comment by qligier** [comment]
I'll do a clean reinstallation of the dev branch to retry. My current installation has maybe seen too much photo duplicates and different versions of the script. But if you've got no error it should be good.

**Pull request merged**
