### PR TITLE
Added import event

### PR DESCRIPTION
**Pull request by mhp**
Hi,

I've written a simple import plugin [here](https://github.com/mhp/Lychee-FlashAir) and to make it work, I needed to add an event to the server import logic.  Here is that change, along with two other minor tweaks I needed: delete files on import, and show current plugins.

Feel free to take none, some, or all of these changes if you think they are helpful!  I think they will apply to either `master` or `v3.0.0` branches, but I have tested against `master`.

### CODE REVIEW

**Comment by electerious** [comment]
There're several problems with `unlink`:
1) It won't work most of the time, because users upload with a different user and the php-user doesn't has the required rights to delete the photo. This could lead to confusion as it depends on your installation.
2) (Empty) folders will stay
3) You can enter a custom path when importing via Lychee. This could lead to security issues. Strangers with access to your Lychee would be able to delete photos from your server.

I'm not entirely sure about this anymore, but I think the default way to fire a plugin action was:
```php
# Call plugins
$this->plugins(__METHOD__, 0, func_get_args());
```
As `$this` isn't available in a static function, the right way of calling the trigger should be something like this:
```php
# Call plugins
self::plugins(__METHOD__, 0, func_get_args());
```
Could you give this a try?

**Comment by electerious** [comment]
Is it ok for you if I add FlashAir to the list of Plugins? https://github.com/electerious/Lychee#plugins-and-extensions

**Comment by mhp** [comment]
I can't use `self::plugins` as that method (defined in `Module.php`) uses instance variables (specifically `$this->plugins`) which are undefined when we don't have an actual object.  This can be fixed by removing the `plugins` method from `Module` and pushing the functionality down into the `Plugins` class itself, possibly by adding a `before` and `after` method.  If you like, I can make a PR with some proposed changes for refactoring this part separately.

I also can't use `func_get_args()` as this returns the arguments that `Import::server` was originally called with, and I need the possibly updated version of the `path` variable.

I agree that the `unlink` fix may be confusing.  How about if I only call it if `$path===LYCHEE_UPLOADS`?  Then importing from a custom directory won't try to delete the photos.  Another way that might work would be for plugins to be able to maintain state between the `before` and `after` triggers, so I could keep a list of the photos I have downloaded and delete them once they are done, but I think this might require bigger changes to how plugins work.

Finally, it is fine if you want to list the plugin, but you might want to wait until it works with your version of Lychee!

**Comment by electerious** [comment]
Thanks for the explanation! Lets do the plugin call your way, but with a comment about why we are calling the function directly. Maybe it would be good to adjust the Import-Module later, so it works without static functions (just like Album, Photo etc.).

`unlink` should be removed for now. Maybe I will find a better solution.

**Comment by mhp** [comment]
I've updated my plugin to build a list of imported files during the `before` trigger, and then delete them during the `after` trigger.  This means I don't need to unlink the files in the  `Import::server` function, so I've removed that part from this PR.  I've also added a comment explaining why the plugin trigger doesn't match the usual form, as you mentioned.

I think that's everything!

**Comment by electerious** [comment]
Added the plugin to the list: https://github.com/electerious/Lychee/commit/f3ce2de49f70ca24a877fad7af3da5a6759bbc3d

**Pull request merged**
