### PR TITLE
Feature/63 video support

### PR DESCRIPTION
**Pull request by CarlAmbroselli**

### CODE REVIEW

**Comment by rhurling** [comment]
Thank you for reopening this @CarlAmbroselli.
I hope I can continue to work on this this weekend.
see https://github.com/electerious/Lychee/pull/343#issuecomment-103816763

**Comment by rhurling** [comment]
It uses [MediaElement.js](http://mediaelementjs.com/) to provide Cross-Browser video support with a Flash Fallback and currently allows mp4, flv, webm and ogv.

To Do:
- [x] Support WMV (video/x-ms-wmv)
- [x] Allow upload of unsupported video types for direct download (avi, mov, mkv, ...)
- [x] Use AddType for supported video types in .htaccess to set correct headers in Apache
- [ ] Add/Set Thumbnail for video
- [ ] Add default Thumbnail (Maybe something using the Iconic "video" Icon)
- [ ] Upload from browser (only Import from Server at the moment)
- [ ] Build MediaElement.js JavaScript and CSS with Gulp into dist/* files (I added them to paths.main but it didn't work)
- [ ] Add Database Schema change
- [ ] Fix "janky" CSS transitions on switch from default to `.full`
- [ ] Change Actions

Folder / Database Changes:
- Adds uploads/video folder and corresponding constants
- Adds `media_type VARCHAR(10) DEFAULT 'photo'` to lychee_photos

(Just copying the ToDo-List from the other Pull-Request)

**Comment by electerious** [comment]
Hey @rhurling, I quickly scrolled through all your changes and they look good. However, I personally prefer a dependency-free solution without MediaElement.js. A Flash-fallback isn't needed and the default player should do everything we need.

**Comment by computaholic** [comment]
Hi, this is a great feature! Will this further be investigated? I am just asking b/c I think this is prop the most wanted feature.....:)

**Comment by Aidenir** [comment]
I'm currently working on some of the points on the checklist:
* [x] Add Database Schema change
* [ ]  Add/Set Thumbnail for video (I extract a frame from the video, which I plan to process in the same way photos are processed)
* [ ]  Add default Thumbnail (Maybe something using the Iconic "video" Icon) (While I'm the process of making the thumbnail I'll have a look into how this can be done)

Btw I noticed that a video does not stop playing when the back arrow is pressed, Will look at this as well if I get time :)

**Comment by Aidenir** [comment]
I don't know the etiquette for continuing work on non-merged pull-requests, but in any case, if someone follows my repo I have now fixed these two as well:
* [x] Add/Set Thumbnail for video (I extract a frame from the video, which I plan to process in the same way photos are processed, hopefully I'll get this working tomorrow)
* [x] Add default Thumbnail (Maybe something using the Iconic "video" Icon) (While I'm the process of making the thumbnail I'll have a look into how this can be done)

**Comment by Aidenir** [comment]
* [x] Upload from browser (only Import from Server at the moment)

**Comment by CarlAmbroselli** [comment]
Any chance that this pull request will be merged into the repository?

**Comment by ryanaverill** [comment]
Any chance we ever added support for Video uploads?

**Comment by Aidenir** [comment]
Most likely no, @electerious has stated a few times in other issues that he does not have eny plans on adding (or merging) video support. In part since he only wants php as a dependency (and noone has figured out how to make thumbnails using only php) and in part because he says video is a whole other beast than photos to work with.

I have more or less finished the work on this branch, which is available in my repo, but I will not maintain the video-only branch separately from my other changes (multiuser and cookies-sessions right now).

**Comment by computaholic** [comment]
Hi, I am no developer nor have I experience in php, but I found this: https://gist.github.com/adamjimenez/5917897

This generates the thumbnails on the client side using html5 and canvas. The idea could be, that thumbnails are generated within the browser and then uploaded to be reused once you visit the site again. In all other cases default thumbnails can be used.

I don't know of this helps, but the video feature would be really great. This imho decides whether lychee is for photographers only or whether it can be used in a more (modern) mainstream way. Because, we all do take videos on vacation, why store them separately?

**Comment by Aidenir** [comment]
@computaholic That is certainly a way to do it, but it feels like a pretty bad option to do this client-side, since then import from server and dropbox wouldn't work.

The way I did it was to use ffmpeg, which feels like a pretty basic dependency, in my opinion, but then again I only use VPSs and my own servers. If one uses a web hosting provider then you might just have php. However since there are quite a lot of php module dependencies, I see no real reason to "ban" ffmpeg.

**Comment by computaholic** [comment]
Another approach could also be to implement the video feature as a plugin, which registers a filetype to lychhee and provides functions on how to deal with thumbnailing, displaying and so on. However this probably would mean major rewrites within lychee. 

Still, @electerious come on, ffmpeg cant be that bad after all, and the availability could be checked during installation and if its not there, video will not work. (Plugins would be great to deal with this).

**Comment by Peque** [comment]
Any updates on this matter? :blush:

**Comment by UdoKifferbrehl** [comment]
I like this a lot too 👍🏻

**Comment by lenisko** [comment]
As I saw original application was changed... and updates for this one? would really like to see videos in this gallery :)

**Comment by westframe** [comment]
Same here, we got problems. Would love to be able to at least upload the video (from iPhone). Any updates?

**Comment by renegaders** [comment]
Hello there.
Not an efficient programmer, but, is video support being added, or in the near future?

Also, a "buy" (add to cart) would be great where people can purchase images?!

Thank you

**Comment by electerious** [comment]
This PR will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community.

**Pull request closed without merging**
