### PR TITLE
Full Screen and Social Sharing Options for Albums

### PR DESCRIPTION
**Pull request by jnsnkrllive**
Adds options to control access to the full screen button and the social sharing buttons on an album.

Sharing Options:
image

Full Screen button on the photo view:
image

Social Sharing buttons on the album view:
image

Social Sharing buttons on the photo view:
image

### CODE REVIEW

**Comment by skyway22** [comment]
Great! Can you do also sharing with bbcodes and stuff? And if have time also resizing photos?

**Comment by jnsnkrllive** [comment]
@skyway22 

BBCode is a markup language commonly used in online message boards. Lychee already provides access to the image file with a link
image
and that can easily be insterted into the BBCode corresponding to the image tag, something like this:
[img]http://lychee.website/path/to/image.jpg[/img]

Resizing photos is not really related to the enhancement in this pull request.

**Comment by electerious** [comment]
@jnsnkrllive Hey, thanks a lot for the PR. I'm sorry but it's currently not planned to add an option to enable/disable sharing. What speaks against the buttons?

I'm also against "Enable Full Screen View" as long as Lychee isn't able to zoom. Viewing big photos on small screens is a pain without a full-screen button. I planned to couple it with the download-option when we have a proper zooming feature.

**Comment by jnsnkrllive** [comment]
@electerious Thanks for considering my PR. I really appreciate the hard work you have put into this project, and have found it very useful already. For my personal use of Lychee, I wanted to restrict access to the photos as much as reasonably possible, which was more than the current version allowed. The two options I identified first for restricting access were the social sharing buttons, and the full screen view.

I did look through the issues before to see if other were interested in the same restrictions. For example, at least 1 other person has wanted a way to disable the social sharing buttons (Issue #570).

As for the "Enable Full Screen View", this option was specific to my deployment and was part of my overall goal of restricting access to the source photo files as much as possible. Since there was already an option for downloading, I thought it would be appropriate to also have an option for the full screen view since they are related and shown in the same menu. It sounds like you have future plans for the download option and proper zooming, so maybe this option could be incorporated once that enhancement is added.

I think most people will find the social sharing buttons and the full screen view useful, and probably would not want to disable those options. But for the smaller group of admins who want to restrict access, I think at least having the option to easily do that would be nice.

**Comment by electerious** [comment]
This PR will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community.

**Pull request closed without merging**
