### PR TITLE
Add video support

### PR DESCRIPTION
**Pull request by rhurling**
This PR adds video support, see electerious/Lychee#63

It uses [MediaElement.js](http://mediaelementjs.com/) to provide Cross-Browser video support with a Flash Fallback and currently allows mp4, flv, webm and ogv.

To Do:
- [x] Support WMV (video/x-ms-wmv)
- [x] Allow upload of unsupported video types for direct download (avi, mov, mkv, ...)
- [x] Use AddType for supported video types in .htaccess to set correct headers in Apache
- [ ] Add/Set Thumbnail for video
- [ ] Add default Thumbnail (Maybe something using the Iconic "video" Icon)
- [ ] Upload from browser (only Import from Server at the moment)
- [ ] Build MediaElement.js JavaScript and CSS with Gulp into dist/* files (I added them to paths.main but it didn't work)
- [ ] Add Database Schema change
- [ ] Fix "janky" CSS transitions on switch from default to `.full`
- [ ] Change Actions

Folder / Database Changes:
- Adds uploads/video folder and corresponding constants
- Adds `media_type VARCHAR(10) DEFAULT 'photo'` to lychee_photos

### CODE REVIEW

**Comment by rhurling** [comment]
Soo... no video support (wontfix) or should i reopen against master?

**Comment by electerious** [comment]
Sorry, has been out-closed by GitHub because I deleted the v3.0 branch. Please reopen against master.

**Comment by rhurling** [comment]
Ah, okay^^ I didn't know GitHub does that.
I'll reopen it tomorrow against master.

**Comment by CarlAmbroselli** [comment]
Any problems with reopening it?

**Comment by brismuth** [comment]
@rhurling just wondering if there were any issues reopening the pull request. Thanks!

**Comment by rhurling** [comment]
Yeah, sorry about that.
I suddenly had (and currently have) way more to do at work than I thought and I have to admit that I'm not sure when I'll be able to continue working on this.
I'll try to do something this weekend.

**Comment by bpiel** [comment]
@rhurling Thanks for getting this started. I'm going to try to find time to pick up this branch. Do you have any advice on how to proceed? thanks

**Pull request closed without merging**
