### PR TITLE
set album input title maxlength to varchar(50) length

### PR DESCRIPTION
**Pull request by ophian**
References #305 and #325
If need, set display length by css

### CODE REVIEW

**Comment by electerious** [comment]
What happens when you set an album title of 50 chars including specials chars like ä, ö, ü etc.? I guess they will take more space than the allowed 50 chars of the database field.

**Comment by ophian** [comment]
No, that works well.

**Comment by ophian** [comment]
hmm sorry, no it does not - after a reload. The size shown will be size minus the amount of umlaut chars.

**Comment by electerious** [comment]
I will update the database field with the next version (>3.0), so the title can contain more chars. Than we can adjust the limit in the Front-End.

**Comment by electerious** [comment]
PR has been out-closed by GitHub because I deleted the v3.0 branch. Will take care of it.

**Comment by electerious** [comment]
A length of 50chars is now allowed (see develop branch).

**Pull request closed without merging**
