### PR TITLE
Feature/subalbums

### PR DESCRIPTION
**Pull request by electerious**

### CODE REVIEW

**Comment by Cilyan** [comment]
Just configured here on a fresh install. The first problem that comes to me, is that if you protect a top level album with a password, it will be asked again when you enter the sub-album. Then on several occasions, I was sent back to the home page, but with a "#identifier" afterwards, and this resulted in an empty page. Title is "Albums", like the home page, but everything is gone.

**Comment by urzhiataer** [comment]
just install this branch on a fresh install

very usefull for me. I use it without password, so no problem. I hope this will be push in the main branch soon

**Comment by haivala** [comment]
Waiting for this to main branch.

**Comment by oyvine** [comment]
I am really looking forward to this feature. I have a large Gallery3 site I want to recreate in Lychee. The structure is a simple two level (Album=year) -> (Subalbum=Happening) -> (Photos). This branch probably has all I need but I am reluctant to try it as I am afraid that it will break once the proper version is out. Do you think it is safe and future-proof to go for this now or should I wait on the real version?

**Comment by haivala** [comment]
@electerious do you have plan with the merge?

**Comment by haivala** [comment]
@electerious so no plans?

**Comment by haivala** [comment]
If this is not going to be merged should this be converted to plugin or extension? we really need this because it has so many use cases.

**Comment by haivala** [comment]
@electerious could you please say something?

**Comment by Darksurf** [comment]
Very excited to see this!

**Comment by ayleid** [comment]
I've also been interested in this for a very long time now. It'll be an extremely useful and exciting feature. :)

**Comment by haivala** [comment]
@electerious still waiting for reply..

**Comment by imthenachoman** [comment]
Does this mean that the latest version will support sub-albums?

**Comment by haivala** [comment]
I have been asking comment from @electerious for 8 moths now... annoying, but I'm still waiting..

**Comment by mcronce** [comment]
This would be really nice to have.  I want to make a switch to Lychee for visual and performance reasons, but multi-level-deep albums is a hard requirement for me

**Comment by haivala** [comment]
Waiting..

**Comment by Neffez** [comment]
Please :(

**Comment by Unthred** [comment]
Would love to switch to Lychee, it looks great and is fast, unfortunately nested albums is a requirement for me. It looks like most of the work has already been done. Is it something you are still working on and if so is there any chance of a rough ETA?

Keep up the great work!

Thanks

**Comment by haivala** [comment]
is this coming to the new repo? https://github.com/LycheeOrg/Lychee

**Comment by fly-man-** [comment]
@haivala Yes, it will come to the new repo but since there's a issue with some of the pieces in this it needs deeper investigations

**Comment by electerious** [comment]
This PR will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community.

**Pull request closed without merging**
