### PR TITLE
Drag and Drop Sorting using Jquery-ui

### PR DESCRIPTION
**Pull request by globalchangemedia**
Hi, I wanted to share an implementation which solves [Feature] Manual sort order #192. 
This adds a dependency (jquery-ui) so that photos can be dragged and dropped to rearrange their order. An INT "position" field needs to be added to your lychee_photos table for this to work and update "sortingPhotos" in settings to "ORDER BY position ASC". 

On the server side it re-orders the whole album collection on every update to preserve _0-n_ ordering, so may become slow for extremely large albums.  

[lychee.zip](https://github.com/electerious/Lychee/files/1448055/lychee.zip)

### CODE REVIEW

**Comment by fly-man-** [comment]
@globalchangemedia You were unable to make it into a pull request from your branch ??

**Comment by globalchangemedia** [comment]
@fly-man-  "position" should be added to the lychee_photos database table as an INT. It then functions to define the Photo position within the Album. Does that answer your question? 

Apologies that I was unable to make this a formal pull request.

**Comment by fly-man-** [comment]
@globalchangemedia As you can see from the commit, position is added to the database as an INT.

But when you open the Options menu and go to Settings, you are presented with the options how to sort an Album and Photo's. To change that to work with positioning, i'd have to add a new option. My question was what to name that option so it will trigger the ORDER BY position ASC

Example: 
settings

**Comment by fly-man-** [comment]
This PR has been merged in a bulk merge.

**Pull request closed without merging**
