### PR TITLE
Spelling corrections

### PR DESCRIPTION
**Pull request by RobLui**
Corrections

### CODE REVIEW

**Comment by RobLui** [comment]
You sure those changes should return back to previous? If you read the text, you get a calmer feel when reading in 2 sections (with the , as separator) vs reading it as 1 long line of text :)

**Comment by fly-man-** [comment]
Yes please, I think the text is long but easily readable

**Comment by RobLui** [comment]
Done, changed :)

**Comment by fly-man-** [comment]
Merged

**Pull request merged**
