### PR TITLE
Internationalization!

### LINKED ISSUE #207: Translation
If you are interested, I can translate it into french.
A translation plugin would be great !

### PR DESCRIPTION
**Pull request by myfreeweb**
I don't know if you'll accept this... but this had to be done for work purposes :) Fixes #207.

Uses [messageformat.js](https://github.com/SlexAxton/messageformat.js) and [moment.js](http://momentjs.com) for dates.

P.S. Please don't align with tabs. Ever. _Indent_ with tabs, but _align_ with spaces.

### CODE REVIEW

**Comment by electerious** [comment]
WOW! This is amazing. I will try to take a closer look at it, but this takes some time. Thanks for the work. You might want to take a look at the v3.0 branch. A lot of stuffed has been changed. I hope there's a way to bring both versions together (v3.0 is still in development).

Where's your problem with tabs?

**Comment by myfreeweb** [comment]
The purpose of tabs is to be configurable without changing the file.
Alignment is supposed to, well, *align*.

The result:

screen shot 2015-03-21 at 1 15 27 am

**Comment by CryssDOTnet** [comment]
I am new to github. Can you explain me what I have to do in order to add a German version and contribute it to the repository? (Linux)

**Comment by CarlAmbroselli** [comment]
@CryssDOTnet 
Have a look at this folder: https://github.com/myfreeweb/Lychee/tree/master/src/i18n

**Comment by ThomasDK81** [comment]
Would love this!

**Comment by electerious** [comment]
This PR will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community.

**Pull request closed without merging**
