### PR TITLE
Check if a user is logged in before displaying log or seeing system information

### LINKED ISSUE #420: displaylog and check plugins are public

### PR DESCRIPTION
**Pull request by Bramas**
This resolves #420

For the check plugin, I let any user see the warnings this can be changed maybe.

This is my first PR on github!!! I hope everything is ok.
I made it because I think the Lychee is awsome!!

### CODE REVIEW

**Comment by electerious** [comment]
Thanks for the PR. I understand your point. The reason for keeping them public: It helps to debug when the installation or an update failed. It's not possible to login in those cases.

**Comment by Bramas** [comment]
That's why I left the errors public.
The warning also are still public since they do not reveal local information.
However, I really think the log (and the system information) must be hide.

**Comment by Bramas** [comment]
Do you want me to change something for the PR?
I really think this should be fixed quickly since the log and the system information may contains some private information and are currently public for every Lychee websites.

I took care of leaving the errors and warnings public in the check plugin because they are here for debug (and they do not contains sensible informations)

**Comment by electerious** [comment]
Merged it manually into `develop`. Thanks a lot! It will be part of Lychee [3.0.9](https://github.com/electerious/Lychee/pull/444).

**Pull request closed without merging**
